// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAjehBmBZEZkd6k4Wli20EUDuHNRbrx2A',
    appId: '1:815386719806:web:97b24daceca4ba0e9ec36f',
    messagingSenderId: '815386719806',
    projectId: 'checkout-c14bc',
    authDomain: 'checkout-c14bc.firebaseapp.com',
    storageBucket: 'checkout-c14bc.appspot.com',
    measurementId: 'G-9W3EEWZFFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoog7PD7JsPKhtMdv12bEWqu-F3Zx7Euo',
    appId: '1:815386719806:android:f4e399b85bd2bd519ec36f',
    messagingSenderId: '815386719806',
    projectId: 'checkout-c14bc',
    storageBucket: 'checkout-c14bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLn9dtvGwRR9jCR3-8bxAXvNYl6duLzsA',
    appId: '1:815386719806:ios:5bf12bd19807b5ab9ec36f',
    messagingSenderId: '815386719806',
    projectId: 'checkout-c14bc',
    storageBucket: 'checkout-c14bc.appspot.com',
    iosClientId: '815386719806-ttusg625n9q9h0j0o8tb7fb3qpr9vr0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLn9dtvGwRR9jCR3-8bxAXvNYl6duLzsA',
    appId: '1:815386719806:ios:5bf12bd19807b5ab9ec36f',
    messagingSenderId: '815386719806',
    projectId: 'checkout-c14bc',
    storageBucket: 'checkout-c14bc.appspot.com',
    iosClientId: '815386719806-ttusg625n9q9h0j0o8tb7fb3qpr9vr0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkout',
  );
}
